Fix jpg.cc for MinGW-w64 (#3821)
* Fix jpg.cc for MinGW-w64

Fix the following error when building with MinGW-w64:

```raw
lib/extras/enc/jpg.cc:277:34: error: cannot convert 'long unsigned int*' to 'size_t*' {aka 'long long
unsigned int*'}
  277 |   jpeg_mem_dest(&cinfo, &buffer, &size);
      |                                  ^~~~~
      |                                  |
      |                                  long unsigned int*
```

* Update jpg.cc

Use LIBJPEG_TURBO_VERSION to detect if libjpeg-turbo is used

* format

---------

Co-authored-by: Moritz Firsching <firsching@google.com>