Fix compilation on system which requires -latomic
box_list is build as a static library, thus all symbols must be
resolved. On some architecture (eg. armel), c11/atomics is implemented
in a library.

Fix compilations errors:

    /usr/bin/ld: tools/box/libbox.a(cache_aligned.cc.o): in function `std::__atomic_base<unsigned long long>::load(std::memory_order) const':
    /usr/include/c++/12/bits/atomic_base.h:488: undefined reference to `__atomic_load_8'